### ISSUE TITLE
Updated RetroPie, Lost wifi

### ISSUE THREAD

**Issue by claytonsulby** [kiteretro/Circuit-Shield#3]
I updated my RetroPie software using `apt get update` and `apt get upgrade` and I have lost communication with the wifi device.

I have also run `sudo /home/pi/Circuit-Shield/update.sh` and `sudo /home/pi/Circuit-Shield/install.sh YES` but have not been able to connect to the wifi device.

On using the wifi settings in retro pie, choosing option 1 "Connect to WiFi network" I receive the message `No wlan0 interface detected`

I wish I hadn't updated! Is there a fix? I am unable to ssh but the onscreen keyboard suffices.

**Comment by kiteretro** [comment]
Hi, you will need to re-burn the image to the SD card to get wifi back. The image contains custom wifi drivers, which are tricky at best to get working and are tied to the kernel version. By doing the `upgrade` it updates the kernel, so that was the problem! From the ES menu you can chose 'update software' and it asks you 'do you want to update kernel packages' and you should press NO to that.

The included kernel is "fairly" recent, unless there is a feature required from a newer kernel I wouldn't worry about upgrading it. If in the future there is a need shoot me a message and I'll see if I can produce a new image with the drivers etc..

**Comment by claytonsulby** [comment]
Wow thank you! I was reading your [circuit sword thread](https://github.com/kiteretro/Circuit-Sword/issues/56). Thanks for the heads up. I'm backing up my important files now to transfer on my next build. Should be fixed in a day or two.
