### ISSUE TITLE
White Screen on boot using CM3+

### ISSUE THREAD

**Issue by claytonsulby** [kiteretro/Circuit-Shield#4]
Booted using CM3 perfectly well but when exchanging the CM3 with the CM3+ (32 gb), the Circuit Shield now only displays white screen.

I initially tried using my original build without re-flashing, that's when the white screen started. I retried the Circuit-Shield-Software-v1.0.1 but am met with a white screen as well. All 3 led's are on, the speaker makes a noise, and the screen dims, but nothing else.

**Comment by kiteretro** [comment]
Hi, you are using the CM3+ WITH eMMC. This means that the SD in the SD slot is NOT used. If you wanted to use the SD slot you must use the "LITE" version of the compute module.

It is possible to flash the onboard 32GB eMMC, what you need to do is:

1. Power off, make sure the CM3+ with eMMC is in the slot, remove the SD (not that it matters, but remove it)
2. Change the little DIP switches on the main board so that "PI-PASSTHRU" and "PROG-EN" are enabled
3. Plug in a battery, and then a USB C cable to your PC. The USB C must support data (not just a charging cable)
4. Turn the CS switch ON, you'll get a white screen and your PC should detect 'something' (it'll make the USB connected noise)
5. You need to download the rpi-boot app, and run it, here are the steps: https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md
6. Once that is done, it should finally appear as a USB drive, from here you can then flash it "as if it were an SD card"
7. Once done, change the DIP switches back so that they are ALL OFF

OR, buy the 'LITE' module ;)

**Comment by claytonsulby** [comment]
Wow! That's quite a process, but it's really convenient you built all that into your board! I'll give it a shot and close when I get it booted.

Does an eMMC board allow for SD as external storage?

**Comment by kiteretro** [comment]
Nope the eMMC basically replaces the SD data lines. Electrically speaking eMMC == SD cards, it's just like a 'solderable SD card' and so if you get the eMMC version of the CM3, all they have done is attach it to the SD traces and then disconnected the ones from the edge connector!

If you wanted more detail, TECHNICALLY there is a '2nd SD card connection' on the CM3 in the form of the 'SDIO' data lines. However on the Circuit Sword these are used for the WiFi adapter :)

**Comment by claytonsulby** [comment]
Went with the CM3+ Lite, and I'm still getting a white screen. I am getting sound so the os is loading from the micro sd card but the screen is not working.

Switched back to a standard CM3 also and the screen boots back up again so It's something related to the CM3+. I have another CM3+ so I'll check that to see if it's just that one board.

**Comment by kiteretro** [comment]
Changing nothing and going back to the CM3 (non-plus) does that go back to working? Which image did you use? Which LCD are you using? Can you reseat all connectors? Maybe some pics?

**Comment by claytonsulby** [comment]
- Changing nothing and going back to CM3 (non-plus) goes back to working
- I used the Circuit-Shield-v1.0.1 image
- I am using the 320x240 LCD screen included with the AIO board

I can reseat the connectors and take images next.

**Comment by kiteretro** [comment]
For some reason I thought this was on a Circuit Sword, not Shield.. my bad (sorry about the screen questions, also the steps to use the eMMC versions doesn't apply to the Shield! For anyone who sees this, for the Shield you need to enable the solder jumper "CM_PROG" which is under where the CM3 is, and then you need to solder a USB cable from the USB A port to another USB A that goes into your PC (because the USB A on the Shield is directly connected to the USB lines of the CM3))

Ok.. so I don't quite know what is going on.. there were some special files to get the + version to work, and they are applied to that image, and also the fact you get sound means it must be booting... but a white screen is either a poor init (so a full power off and power back on will sort that out) or a bad connection on the CM3 module... did you have any luck re-seating the CM3+ all the way to the back of the connector?

**Comment by claytonsulby** [comment]
Switched to a different CM3+ and worked instantly. Probably something with the unit, but thanks for the tip about the USB! If I ever feel like using the CM3+s with the eMMC I'll go that route.
